apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudhelm-controller
  namespace: cloudhelm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudhelm-controller
  namespace: cloudhelm
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudhelm-controller
  namespace: cloudhelm
subjects:
  - kind: ServiceAccount
    name: cloudhelm-controller
    namespace: cloudhelm
roleRef:
  kind: Role
  name: cloudhelm-controller
  apiGroup: rbac.authorization.k8s.io
